kanidm/webauthn-rs

src/attestation.rs, src/error.rs, src/lib.rs
This PR adds support for surrogate attestation type for packed attestation format and solve https://github.com/Firstyear/webauthn-rs/issues/17.
After that change, I was able to use the example web server to register and authenticate with touchID using Chrome (Version 77.0.3865.120).
=> Add support for packed attestation format (surrogate attestation type)

src/proto.rs
TokenBinding is struct (not a string): https://www.w3.org/TR/webauthn/#collectedclientdata-json-serialized-client-data
=> fix tokenBinding client data type

Cargo.toml, examples/actix/actors.rs, examples/actix/main.rs, src/attestation.rs, src/base64_data.rs, src/error.rs, src/lib.rs, src/proto.rs, static/js/webauthn.js
A few minor improvements:
- allow library user customization on register via arguments 
- use snake case and serde rename
- use a custom type to represent base64 url safe, no pad encoded bytes (implement ser/de traits on it)
- expose certain properties to library users (i.e. pub(crate) -> pub).
- WebAuthnError conforms to Error trait now via `this error`.
- [x ] cargo test has been run and passes
- [x ] documentation has been updated with relevant examples (if relevant)
=> W3C Conformance Fixes and Other Minor Improvements

examples/tide/main.rs
=> respect prefix option in tide example

examples/tide/main.rs
=> add redirect to /auth from /

src/lib.rs
=> fix(policy_verify_trust): update documentation to match default impl

examples/tide/actors.rs, src/core.rs, src/proto.rs
This cleans up some of the extension struct naming, and returns the auth_data from registration so that consumers can use this data for their auth processes. 
=> Cleanup naming in extensions, return auth data in registration.

examples/tide/actors.rs, src/attestation.rs, src/base64_data.rs, src/core.rs, src/ephemeral.rs, src/proto.rs
Implements #61.
* Adds `ChallengeRef`, to allow working with `Challenge`s in the same way that `&[T]` and `Vec<T>` are used.
* This adds a small amount of unsafe code, but it is very mundane as far as unsafe code goes.
* `Webauthn::register_credential_internal()` takes `chal` and `exclude_credentials` by reference.
* `Webauthn::register_credential()` takes `state` by reference.
* `Webauthn::authenticate_credential()` takes `state` by reference and returns a reference to a `CredentialID`.
* `WebauthnConfig`'s methods:  `get_relying_party_name` and `get_relying_party_id` now return `&str` instead of `String`.
* I'm not sure if this is ideal. I understand that webauthn_rs code currently needs to clone these `&str`s anyways, but the trait was asking that the implementer perform `&self -> …
=> Refactor functions to take more arguments by reference

examples/tide/actors.rs, src/attestation.rs, src/core.rs, src/error.rs, src/proto.rs
Supercedes #49 - this implements the start of the design as discussed in https://github.com/kanidm/webauthn-rs/blob/master/designs/authentication-use-cases.md
This allows:
* Multiple credentials, with a derive UV policy and checked for consistency.
* A single credential, which can have a policy over-ride applied.
- [ - ] documentation has been updated with relevant examples (if relevant)
=> Authentication Verification Refactor

.gitignore, src/core.rs, src/error.rs, src/proto.rs
Add `crossOrigin` field to `CollectedClientData` and capture unknown keys in an extra field.
Additionally updates some formatting left over from credBlob.
Implements #52.
=> Update CCD to spec

.gitignore, src/base64_data.rs
Adds tryfrom for Base64UrlSafeData so we can convert from Strings
- [ - ] documentation has been updated with relevant examples (if relevant)
=> Try from str base64

src/proto.rs
Currently transports is serialized as null, which seems to be breaking some clients for me that either expect an array or the value to simply be not present.
I've changed it to be skipped when the value is None, matching other optional fields in similar structs.
=> Do not serialize transports when not present

src/attestation.rs, src/core.rs, src/crypto.rs, src/proto.rs
This changes what we parse to policy_verify_trust to be clearer, and moves the ParsedAttestationData out to proto since we may choose to expose this to consumers later. 
A lingering question is what we return from `register_credential`. Currently we return `Result<(Credential, AuthenticatorData<Registration>), WebauthnError>` but outside of the extensions in authenticator data, this is not very useful.
I think we should consider changing this to return ParsedAttestationData instead, and moving the Registration extensions into PAD, which is "nicer" for consumers to then consume.
I think PAD should be left as NOT ser/deser because I think it should be up to consumers to save what they want from the structure in a way that is compatible and auditable for them.  …
=> Extend registration metadata options

src/crypto.rs, src/proto.rs
Based on feedback from https://bugzilla.suse.com/show_bug.cgi?id=1187632 use constants for keytype id
=> Use constants based on review feedback

README.md, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/internals.rs
=> Add windows 11 hello to broken hw list

README.md, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/internals.rs
Given [this bug report][1], #105 appears to be a Firefox 98 bug, not a Windows
11 bug. To confirm, I tested that Firefox Nightly (version 100) on both Windows
10 and 11 does exhibit this bug, while Firefox 98 does exhibit this bug on
Windows 10 in addition to Windows 11.
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1759098
=> Windows 11 bug is actually Firefox 98 bug

webauthn-rs-core/Cargo.toml, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/error.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-demo-shared/src/lib.rs, webauthn-rs-demo/src/actors.rs, webauthn-rs/src/lib.rs
Fixes #114  Fixes #108 - this adds a cfg feature allowing rs1 to be disabled. Additionally, an experimental internal only flag is added to reject credentials with a counter of 0 which likely indicates a passkey and a credential that is synced between multiple devices. 
=> 114 108 detect rs1 passkeys

tutorial/site/src/main.rs, webauthn-rs-core/Cargo.toml, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
Add extra metadata to keys and improve key loading and conversion from older versions.
=> Add extra metadata to registered keys

webauthn-rs-core/src/core.rs, webauthn-rs-core/src/error.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs, webauthn-rs/src/lib.rs
This adds support for the upcoming authenticator backup state flags, as well as modifies our policies to handle these and expose them in credentials. 
=> Add support for authenticator backup states

webauthn-authenticator-rs/src/lib.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs
This improves some backup state management flag handling. It also allows re-attestation of the credential post-registration. It also adds the ability to return which CA provided the attestation of the credential.
The question I have is *how* we should return that CA that did the attestation. Should we put the attestation CA into the Credential? Should we just return it as a tuple from `register_credential()`? Or should we do something else? 
=> 20220613 ca management

base64urlsafedata/Cargo.toml, base64urlsafedata/src/lib.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/interface.rs
Fixes #140 this changes how base64urlsafe works to allow it to decode from a raw byte array or the base64, so we can handle inplace upgrades. It means credentials should appear now as:
```
{"cred_id":"uZcVDBVS68E_MtAgeQpElJxldF_6cY9sSvbWqx_qRh8wiu42lyRBRmh5yFeD_r9k130dMbFHBHI9RTFgdJQIzQ","cred":{"type_":"ES256","key":{"EC_EC2":{"curve":"SECP256R1","x":"wn5_bfwXgxX8Bt9jLP6MG-YRXgWFHGgpkEWrlaEayPM","y":"j3u3nBiyFfh1n6JFqzS8_Bo7Bi9nXBM6dWf5ANsIX8Q"}}},"counter":2,"user_verified":false,"backup_eligible":false,"backup_state":false,"registration_policy":"preferred","extensions":{"cred_protect":"NotRequested","hmac_create_secret":"NotRequested"},"attestation":{"data":{"Basic":["MIICvTCCAaWgAwIBAgIEK_F8eDANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4 …
```
=> Convert cosekeys to use base64urlsafe internally

compat_tester/webauthn-rs-demo/src/main.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs, webauthn-rs-proto/src/attest.rs, webauthn-rs-proto/src/auth.rs, webauthn-rs-proto/src/extensions.rs, webauthn-rs/src/interface.rs
Dug around in the code a bit and eliminated most of the clippy errors I could find. Mostly that consisted of removing redundant .clone()s, references that are destructured, and converting some of the intos into From. There are still some left, but 3 of them require rewriting some functions with tons of inputs, 1 of them is an ugly bit based nom function, and 2 of them refer to Intos that I didn't convert because serde is deriving stuff from them.
=> Did some housecleaning for Clippy v2

tutorial/server/axum/Cargo.toml, tutorial/server/axum/src/auth.rs
This brings axum-sessions up to the latest version. The primary change
is how sessions are extracted, namely that axum-sessions now provides a
ReadableSession and WritableSession. Otherwise things remain unchanged
and should continue to function as before.
Note that the axum example currently sets secure to true, which means
the example won't work in some browsers (Safari, for instance) unless
it's in fact secured; Tide sets this to false by default.
Fixes #
=> update axum-sessions to v0.3.0

webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs
Fixes #169 - add support for TPM's with ECC algorithms including validation of their pub area data. In most cases this will fail anyway because of the use of SHA1 in the signing chains, but it's good to future proof anyway. 
=> 20220812 tpm ecc

webauthn-authenticator-rs/examples/conformance/core.rs, webauthn-authenticator-rs/examples/conformance/main.rs
Built on top of #172 
This adds an example, `conformance`, which checks for protocol conformance violations. At the moment, it is limited to ISO7816 related issues, but could be trivially extended to capture other sorts of issues.
Example run of `cargo run --example conformance --features nfc` with a Yubico Security Key NFC C:
```
Atr { protocols: [0, 1], t1: [128, 115, 192, 33, 192, 87, 89, 117, 98, 105, 75, 101, 121], storage_card: false, card_issuers_data: Some([89, 117, 98, 105, 75, 101, 121]), command_chaining: Some(true), extended_lc: Some(true) }
Card issuer's data: YubiKey
* Select incorrect applet AID
* Select with truncated Ne
* Select applet with extended Lc/Le (Card reports supporting extended Lc/Le, but doesn't)
* Select with zero Ne (Expected no response data for Ne=0, card …
```
=> Conformance tests for ISO7816

compat_tester/webauthn-rs-demo/Cargo.toml, fido-mds-tool/src/main.rs, fido-mds/src/lib.rs, fido-mds/src/mds.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs, webauthn-rs/Cargo.toml, webauthn-rs/src/lib.rs
Add support to store the TPM version in it's attestation metadata. this can be used in conjuction with the MDS to determine if the device is on an FW version that is trustworthy
=> 20220816 updates for tpm fido

compat_tester/webauthn-rs-demo/Cargo.toml, tutorial/server/axum/Cargo.toml, tutorial/server/axum/src/auth.rs, tutorial/server/tide/Cargo.toml, tutorial/server/tide/src/main.rs, webauthn-rs/Cargo.toml, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
Fixes #170 - Help to document the risks of serialising the reg/auth states with client side held cookies. 
=> Reduce ability for people to accidentally allow replay attacks

authenticator-cli/src/main.rs, webauthn-authenticator-rs/src/u2fhid.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
Fixes #185 - this allows BE to change false -> true on a passkey, and gives RP's the choice to allow that upgrade. 
=> Allow passkey upgrades

webauthn-rs-core/src/core.rs
These (see the test cases) parse as `scheme: "ios"` and `path: "bundle-id:com.foo.bar"` with no `host`, so they don't compare normally. However, if the input urls are exactly matching, i think we can just consider that a match?
Fixes #
=> fix handling of strange origins

.github/workflows/ci.yml
Use [matrixes](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to select the Rust version used by CI, to make it easier to test different features in the future.
This doesn't touch any of the Rust code.
=> Use matrixes for CI

designs/authenticator-library.md
As previously discussed offline with @Firstyear, this documents the current state of the world for `webauthn-authenticator-rs`, and outlines some future work.
=> RFC: authenticator library design proposal

webauthn-authenticator-rs/Cargo.toml, webauthn-rs-core/Cargo.toml
Swap to our cbor 2 library - currently identical in source to serde cbor
=> swap to cbor 2

fido-mds/src/mds.rs
Running `fido-mds-tool` against [current metadata](https://mds3.fidoalliance.org/) returns an error:
```
DEBUG compact_jwt::jws: Invalid Jwt - Serde Error e=Error("unknown variant `rsassa_pkcsv15_sha256_raw`, expected one of `secp256r1_ecdsa_sha256_raw`, `secp256r1_ecdsa_sha256_der`, `secp256k1_ecdsa_sha256_raw`, `rsa_emsa_pkcs1_sha256_raw`, `ed25519_eddsa_sha512_raw`, `secp384r1_ecdsa_sha384_raw`", line: 1, column: 1206200)
ERROR fido_mds_tool: e=InvalidJwt
```
This adds the missing algorithm.
=> Add AuthenticationAlgorithm::rsassa_pkcsv15_sha256_raw

compat_tester/webauthn-rs-demo-wasm/src/compat.rs, compat_tester/webauthn-rs-demo/src/actors.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/proto.rs, webauthn-rs-proto/src/attest.rs, webauthn-rs-proto/src/extensions.rs, webauthn-rs/src/lib.rs
Per discussion on #206, this removes support for the `credBlob` extension:
* `webauthn-authenticator-rs` didn't implement it correctly (#206)
* I could only find _two_ keys in FIDO's MDS which support this (ATKey.Pro and YubiKey Bio)
* [The extension appears to be exclusively used for Microsoft's corporate Active Directory](https://groups.google.com/a/chromium.org/g/blink-dev/c/Vfg2o0peyYg/m/Vp0h8i5VBQAJ)
* The `User.id` supports up to 64 bytes of arbitrary data and is supported by all CTAP2 authenticators (`credBlob` is only 32 bytes)
* The [`largeBlob` extension](https://www.w3.org/TR/webauthn-2/#sctn-large-blob-extension) supports even more data, and appears to replace it
---
=> Remove support for credBlob, per #206

webauthn-rs-proto/src/extensions.rs, webauthn-rs-proto/src/options.rs
* Add `RegistrationExtensionsClientOutputs` fields `hmac_secret`, `cred_protect`, `min_pin_length`
* Add `AuthenticatorTransport::Test`
* Note missing icon for `User` and `RelyingParty`
* Fix `User::name` docstring
Fixes #
=> Add common fields from win10 branch

webauthn-authenticator-rs/src/u2fhid.rs
This appears to have leaked out an earlier version of #204, which added icons.
=> Remove icon support from u2fhid

.github/workflows/ci.yml, designs/authenticator-library.md, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/examples/nfc_token_info/main.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/win10/clientdata.rs, webauthn-authenticator-rs/src/win10/cose.rs, webauthn-authenticator-rs/src/win10/credential.rs, webauthn-authenticator-rs/src/win10/extensions.rs, webauthn-authenticator-rs/src/win10/gui.rs, webauthn-authenticator-rs/src/win10/mod.rs, webauthn-authenticator-rs/src/win10/native.rs, webauthn-authenticator-rs/src/win10/rp.rs, webauthn-authenticator-rs/src/win10/user.rs
This adds support for Windows 10's WebAuthn API. This is effectively mandatory on Windows 10 Build 1903 and later, as it blocks direct access to FIDO authenticators for non-Administrator users.
https://user-images.githubusercontent.com/246847/194449801-4e6b89e5-0465-4dea-8dc9-bf2508373147.mp4
This also adds a new `authenticate` example, pulled from `SoftToken`'s unit tests.
Tasks remaining:
Fixes #
=> Add support for Windows 10 WebAuthn API

base64urlsafedata/src/lib.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/src/softtoken.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/error.rs, webauthn-rs-core/src/interface.rs
Improves #138 - This allows verification of the attested AAGUID and it's association to a specific CA that provided it. This maps cleanly to the fido MDS where a CA can sign multiple AAGUIDS, but an AAGUID must only be signed by a single CA. This is working towards the ability to do strict attestation policy. 
Next step will be to allow converting the fido-mds structures into the Attestation CA. I think I will also improve the Attestation CA and Attestation CA List code into proper builder patterns to assist with this. 
=> Allow checking of aaguids in attestation code.

base64urlsafedata/src/lib.rs, fido-mds-tool/src/main.rs, fido-mds/src/lib.rs, webauthn-rs-core/src/core.rs
Add a test for a (shonky) u2f device, improve fido mds tool to list u2f output.
=> 20221106 test device

webauthn-authenticator-rs/src/win10/credential.rs, webauthn-rs-proto/src/options.rs
Fixes #219 - Add hybrid transport. This is technically only part of the level 3 draft specification, but according to #219 it's now out in the wild. 
=> Add hybrid transport

webauthn-rs-core/Cargo.toml
Fixes #223 Update base64urlsafe to correct needed version. 
=> Update base64urlsafe to 0.1.2

webauthn-authenticator-rs/src/error.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/softpasskey.rs, webauthn-authenticator-rs/src/softtoken.rs, webauthn-authenticator-rs/src/usb/mod.rs, webauthn-authenticator-rs/src/util.rs
Splitting up https://github.com/kanidm/webauthn-rs/pull/215 to make it smaller:
* Improves OpenSSL error handling by making a nice conversion from `ErrorStack` to `WebauthnCError`
* Refactor `softtoken` and `softpasskey` to use simplified code
* Pull `compute_sha256` into `util` module to de-dupe
=> Improve OpenSSL error handling, and pull sha256 function into util

.github/workflows/ci.yml, fido-mds-tool/src/main.rs, fido-mds/src/lib.rs, fido-mds/src/mds.rs, pull_request_template.md, webauthn-rs/src/lib.rs
- Fixes #240 
- Bumps github checkout action to `v3` to solve deprecation warnings
- Introduces `cargo fmt --check` at CI time and remove the related checks from the PR template
=> Doc and CI improvements

fido-mds-tool/src/main.rs, fido-mds/Cargo.toml, fido-mds/src/lib.rs, fido-mds/src/query.rs, webauthn-authenticator-rs/examples/key_manager/main.rs, webauthn-authenticator-rs/src/ctap2/commands/get_info.rs
This adds support for improved querying of the MDS. Currently it only supports aaguid queries but we can expand this to also support other items that may be used by people making decisions. 
=> Add improved query support

webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/build.rs
This checks that OpenSSL has this patch: https://github.com/openssl/openssl/pull/12826
Old versions of OpenSSL report a `malloc failure` part way through a caBLE handshake.
The existing `hkdf_chromium` test reproduces the issue reliably, so just run that test in `build.rs`.
Fixes #
=> Fail builds when running on old/broken versions of OpenSSL

.github/workflows/ci.yml, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/examples/cable_tunnel/core.rs, webauthn-authenticator-rs/examples/cable_tunnel/main.rs, webauthn-authenticator-rs/src/cable/base10.rs, webauthn-authenticator-rs/src/cable/btle.rs, webauthn-authenticator-rs/src/cable/discovery.rs, webauthn-authenticator-rs/src/cable/framing.rs, webauthn-authenticator-rs/src/cable/handshake.rs, webauthn-authenticator-rs/src/cable/mod.rs, webauthn-authenticator-rs/src/cable/noise.rs, webauthn-authenticator-rs/src/cable/tunnel.rs, webauthn-authenticator-rs/src/crypto.rs, webauthn-authenticator-rs/src/ctap2/commands/mod.rs, webauthn-authenticator-rs/src/error.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/util.rs
This implements a subset of caBLE v2.1 based on Chromium's implementation, and can act as both an initiator (acting as a transport for `CtapAuthenticator`) and an authenticator (proxying requests to `AuthenticatorBackendHashedClientData`, handling PIN/UV auth), and is the MVP for #259.
This handles all the Websockets and Noise-like tunnelling needed to make things work:
* If you're using this as an initiator (to authenticate with a mobile device), this generates a QR code, and works with platform Bluetooth APIs (bluez / CoreBluetooth / WinRT) to listen for the service data advertisement.
* If you want to use this as an authenticator (to pretend to be a mobile device) you'll need to provide a way to send service data advertisements (as macOS and Windows don't allow this); there's an …
=> Add basic support for caBLE authenticators / initiators

webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/internals.rs
=> fix rustdoc syntax in webauthn_rs_core

webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/src/ctap2/commands/get_info.rs, webauthn-authenticator-rs/src/ctap2/ctap20.rs, webauthn-authenticator-rs/src/ctap2/ctap21.rs, webauthn-authenticator-rs/src/ctap2/pin_uv.rs, webauthn-authenticator-rs/src/error.rs, webauthn-rs-core/src/core.rs, webauthn-rs-proto/src/options.rs
The way that the `CtapAuthenticator` backend does user verification isn't [what the CTAP spec says to do][0], so this fixes things:
* add `verification_policy` flag to `authenticate` example, and plumb that through
* fix built-in user verification on CTAP 2.1-PRE authenticators
* `CtapAuthenticator` now follows [documented guidance][0] and requires user verification even if `userVerificationPolicy = preferred`; so effectively `required == preferred`
* return `UserVerificationRequired` error whenever a key does not meet verification policies
Related fixing:
* invalidate and refresh `GetInfoResponse` when the authenticator PIN is set, or fingerprint enrolments change
* `webauthn-rs-core`: when authenticating, check for consistent policies rather than trying to specifically use `Preferred` …
=> Fix up user verification with CtapAuthenticator, and minor fixing

.github/workflows/ci.yml, CONTRIBUTORS.md, base64urlsafedata/Cargo.toml, base64urlsafedata/src/lib.rs, fido-mds/Cargo.toml, fido-mds/src/lib.rs, webauthn-rs-core/Cargo.toml, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/internals.rs
Fixes #278 
this upgrades all of the crates within webauthn-rs to using base64
to the latest version 0.21. the interface changed significantly
since 0.13, and although i'm not a huge fan of it, receiving updates
is good, and this is the last crate in my workspace that needs updating
so here i am updating the crate :)
lemme know if there's anything you'd like changed with how we call
the new API's!
=> Update Base64 & MSRV to 1.57.0

webauthn-rs/src/lib.rs
This improves protection of created credentials that are capable of cred protect, by requesting the extension opportunistically or as a requirement. 
=> 20230220 opportunistic cred protect

webauthn-authenticator-rs/src/win10/mod.rs
Windows 10 returns a `WEBAUTHN_ASSERTION` with `dwVersion = 1` if there are no extensions.
It appears this only triggers a null pointer dereference when using a platform authenticator, because it returns an uninitialised `Extensions.cExtensions` value which then ends in dereferencing a null `PCWSTR`:
```
(4ef8.5710): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for authenticate.exe
authenticate!windows::core::strings::pcwstr::PCWSTR::as_wide+0xe:
00007ff7`e8e5f39e 488b09          mov     rcx,qword ptr [rcx] ds:00000000`00000000=????????????????
0:000> k
00 000000be`ff9e9fa0 00007ff7`e8e5f3f5 …
```
=> Null pointer dereference for GetAssertion on Windows 10

compat_tester/webauthn-rs-demo-shared/src/lib.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/src/cable/discovery.rs, webauthn-authenticator-rs/src/nfc/atr.rs, webauthn-authenticator-rs/src/usb/responses.rs, webauthn-rs-proto/src/extensions.rs, webauthn-rs-proto/src/options.rs, webauthn-rs/src/lib.rs
Fixes multiple clippy failures in CI:
* (error) `derivable_impls` for many `Default` implementations (added in new clippy)
* (error) `expect_used` regressions missed in #289
* (error) mismatched `image` library versions from `bardecoder`
* (warning) `wrong_self_convention` in `Eid::to_bytes()`
* (warning) `bool_assert_comparison` in `nfc/atr.rs` tests
* (warning) `box_default`  in multiple places
=> clippy: fix multiple issues

webauthn-authenticator-rs/Cargo.toml
We were pinning a commit of `deviceplug` for a Linux-specific bug fix; but this was only on the upstream `dev` branch.
That commit got stomped due to a force-push of that branch: https://github.com/deviceplug/btleplug/pull/302#issuecomment-1503946059
=> Fix broken deviceplug commit due to force-push of dev branch

.github/workflows/ci.yml, webauthn-rs-proto/Cargo.toml
`actions-rs/toolchain` appears unmaintained, it didn't build with the proper compiler version (unsure whether this was an error in the config), and depends on an old version of NodeJS which is deprecated (and makes noisy warnings).
[All the cool kids][0] are using https://github.com/dtolnay/rust-toolchain
Because this Action actually enforces MSRV checks and uses the correct compiler version, this uncovered some problems:
* https://github.com/kanidm/webauthn-rs/pull/258 bumped axum to 0.6.1, and [its MSRV is 1.60.0][1] ([log][2])
* There are multiple transitive dependencies on `time v0.3.20`, which [requires rustc 1.63.0][3].
* https://github.com/kanidm/webauthn-rs/pull/293 changed to using derived `Default` impl (to address a clippy lint), which only works properly on `rustc >= 1.66.0`, …
=> Switch to dtolnay/rust-toolchain, bump MSRV to 1.66.0

webauthn-rs/src/lib.rs
Fixes #281 In response to this issue we should take proactive steps to prevent client side UV bypassing in our apis. Since firefox is soon to gain CTAP2 support, being the last limiting factor for this, I believe it's time to enforce required UV in passkey flows. Since this won't be released for a bit until some other library changes occur, we can wait for ff to support this by default. 
=> Resolve potential client side UV bypass in passkeys

webauthn-authenticator-rs/src/ctap2/commands/get_info.rs, webauthn-authenticator-rs/src/ctap2/commands/mod.rs, webauthn-authenticator-rs/src/softtoken.rs
This also adds a `Default` impl for `GetInfoResponse`, and makes the Display output a little less verbose when options are missing.
This PR doesn't conflict with others I have in flight, so ordering doesn't matter.
=> Add remaining FIDO 2.1 GetInfoResponse fields

Cargo.toml, authenticator-cli/Cargo.toml, base64urlsafedata/Cargo.toml, compat_tester/webauthn-rs-demo-shared/Cargo.toml, compat_tester/webauthn-rs-demo-wasm/Cargo.toml, compat_tester/webauthn-rs-demo/Cargo.toml, fido-mds-tool/Cargo.toml, fido-mds/Cargo.toml, tutorial/server/actix_web/Cargo.toml, tutorial/server/axum/Cargo.toml, tutorial/server/tide/Cargo.toml, tutorial/wasm/Cargo.toml, webauthn-authenticator-rs/Cargo.toml, webauthn-rs-core/Cargo.toml, webauthn-rs-proto/Cargo.toml, webauthn-rs/Cargo.toml
This makes it easier to track our versions of everything.
This also sets MSRV to 1.66.0 to be consistent with `webauthn-rs-core`.
Fixes #
=> Move common dependencies into workspace

webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/cable_domain.rs, webauthn-authenticator-rs/src/cable/mod.rs, webauthn-authenticator-rs/src/cable/tunnel.rs
=> add CLI tool to derive caBLE tunnel server domain

webauthn-rs-proto/src/options.rs, webauthn-rs/src/lib.rs
This generally improves docs around passkeys and webauthn-rs generally, but also improves the docs around the uv preference options that we recently changed. 
=> 20230416 passkey define

webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/examples/authenticate/main.rs, webauthn-authenticator-rs/examples/cable_tunnel/core.rs, webauthn-authenticator-rs/examples/key_manager/main.rs, webauthn-authenticator-rs/examples/nfc_token_info/core.rs, webauthn-authenticator-rs/examples/nfc_token_info/main.rs, webauthn-authenticator-rs/src/cable/btle.rs, webauthn-authenticator-rs/src/cable/tunnel.rs, webauthn-authenticator-rs/src/ctap2/mod.rs, webauthn-authenticator-rs/src/error.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/nfc/mod.rs, webauthn-authenticator-rs/src/stubs.rs, webauthn-authenticator-rs/src/transport/any.rs, webauthn-authenticator-rs/src/transport/mod.rs, webauthn-authenticator-rs/src/transport/types.rs, webauthn-authenticator-rs/src/usb/mod.rs, webauthn-authenticator-rs/src/usb/responses.rs
Changes:
* Replace `bluetooth` feature with `btleplug` for things that need Bluetooth support. The `bluetooth` feature will be used to activate BTLE authenticator support in #272. 
* Make `AnyTransport::new()` and `Token::cancel()` async
* Use proper async stuff in `key_manager`
* Stub more of `btleplug`
* Extract common request handling layer out of `usb` into common module, as Bluetooth tokens use some of the same things
* Add support for USB PING command
Fixes #
=> API changes needed for BTLE work

.github/workflows/ci.yml
This does a few things to speed up CI tasks:
* build in debug mode (rather than release mode), so the tests don't trigger a full rebuild
* only build the many features with `webauthn-authenticator-rs`, rather than the whole library
* split `cargo fmt` into its own action
* don't run clippy for `webauthn-authenticator-rs` on Windows unless using Windows-specific features
* use sccache
There's more jobs now, but they're smaller jobs, so less likely to block things up when you have a few branches running in parallel.
=> CI performance improvements

.github/workflows/ci.yml
Clippy doesn't like clap's macro expansion on Rust 1.69: https://github.com/rust-lang/rust-clippy/issues/10421
So disable clippy on 1.69 for now.
=> Temporarily disable clippy on Rust 1.69 

.github/doc_manifest, .github/workflows/ci.yml, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/bluetooth/framing.rs, webauthn-authenticator-rs/src/bluetooth/mod.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/stubs.rs, webauthn-authenticator-rs/src/transport/any.rs, webauthn-authenticator-rs/src/transport/mod.rs, webauthn-authenticator-rs/src/transport/types.rs
This adds basic support for using Bluetooth Low Energy authenticators.
Because of API design and UI problems (see #214), the interface is *extremely* flaky and timing sensitive.  Fixing that will be a lot more work (refactoring more of the library to be `async`, and use `tokio` `Streams`); but should be easier to approach building around a transport which has the same model.
However, the important part of actually being able to use BTLE GATT as a transport layer, and being able to frame requests properly with CTAP's variable MTU works.
Tested with:
* Hideez Key 4
* Feitian MultiPass K16
Fixes #
=> BTLE authenticator transport

.github/workflows/ci.yml
This should free up CI capacity when updating PRs / branches.
Example: https://github.com/micolous/webauthn-rs/actions/runs/4826108718
=> Automatically cancel jobs in CI when a revision is obsolete

webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/bluetooth/mod.rs, webauthn-authenticator-rs/src/cable/noise.rs, webauthn-authenticator-rs/src/cable/tunnel.rs, webauthn-authenticator-rs/src/ctap2/commands/make_credential.rs, webauthn-authenticator-rs/src/nfc/mod.rs, webauthn-authenticator-rs/src/transport/mod.rs, webauthn-authenticator-rs/src/usb/mod.rs
This makes things a bit easier to debug.
=> base16 encode tracing output

Cargo.toml, cable-tunnel-server/frontend/Cargo.toml
Crates needs you to publish a version to reserve a name, so publishing current git HEAD for now. I've set these at v0.1.0 until we get proper versioning sorted out.
=> Update metadata for cable-tunnel-server to allow publishing

webauthn-rs/src/interface.rs
Fixes #332 - Incorrect definition of cfg flags prevent cred internal flag working. 
=> Fix incorrect feature flag definition

tutorial/server/axum/assets/auth.js
=> Fix missing base64 conversion of response.userHandle

tutorial/server/axum/src/main.rs
Enables the tutorial to be runnable locally by default. Without this, `finish_register` returns `Err(WebauthnError::CorruptSession)` when running locally.
=> SessionLayer::with_secure(false)

fido-mds/src/lib.rs
Clippy on 1.70.0 fails
- ~~documentation has been updated with relevant examples (if relevant)~~
=> fix redundant clone

fido-key-manager/Cargo.toml
`fido-key-manager` requires elevation on Windows:
* For simplicity, this is declared in the application's manifest, included at link time. Elevation is handled by the platform before it calls `.main`.
* There are ways to conditionally elevate actions, but this is much more complicated to implement. The only thing this tool which _doesn't_ require elevation is `--help`, so this is much simpler.
`cargo` can't launch binaries requiring elevation. There's also no way to detect at a `build.rs` level whether a binary target will be used for a test, and conditionally disable elevation support.
There's no tests in `fido-key-manager` anyway – so this just disables them explicitly so that a project-wide `cargo test` won't fail on Windows.
=> fido-key-manager: disable tests

tutorial/server/axum/assets/auth.js
While investigating #351 I noticed that the `excludeCredentials` id's were still in base64url and which was failing validation in 1Password. Here I mirror the same modifications done to the `allowCredentials` list.
Fixes #
=> Fix axum example for credential creation

webauthn-authenticator-rs/src/win10/user.rs
`WinUserEntityInformation` encoded `User::id` as Base64 – that's not right!
=> win10: fix incorrect user entity encoding

compat_tester/webauthn-rs-demo/README.md
Before #360, `webauthn-rs-demo` would generate a certificate with a SAN. This seems to be required by Chrome on desktop.
This updates the docs to set a SAN.
=> Add subjectAltName to webauthn-rs-demo example

sshkey-attest/src/proto.rs
Expose the sshkeys library at our required commit version for sshkey-attest consumers. 
=> Expose sshkeys

webauthn-authenticator-rs/src/bluetooth/mod.rs, webauthn-authenticator-rs/src/ui/cli.rs, webauthn-authenticator-rs/src/ui/mod.rs, webauthn-authenticator-rs/src/usb/mod.rs
When device selection was added, some operations prompt for touch multiple times (possibly depending on key firmware?), but there's no feedback for "processing" status. This will bubble that up.
However, some keys do weird flip-flops between `Processing` and `UserPresenceNeeded` even when they're still waiting for user presence.
=> Show "processing" status for BTLE and USB keys

.github/workflows/ci.yml, Cargo.toml, fido-key-manager/Cargo.toml, fido-key-manager/README.md, fido-key-manager/src/main.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/bluetooth/mod.rs, webauthn-authenticator-rs/src/ctap2/mod.rs, webauthn-authenticator-rs/src/ctap2/solokey.rs, webauthn-authenticator-rs/src/error.rs, webauthn-authenticator-rs/src/nfc/atr.rs, webauthn-authenticator-rs/src/transport/mod.rs, webauthn-authenticator-rs/src/transport/solokey.rs, webauthn-authenticator-rs/src/transport/types.rs, webauthn-authenticator-rs/src/usb/mod.rs, webauthn-authenticator-rs/src/usb/responses.rs, webauthn-authenticator-rs/src/usb/solokey.rs
This implements some vendor-specific SoloKeys 2 (Trussed) vendor-specific commands:
* get device UUID
* get firmware version
* get lock / secure boot status
* get random bytes
These commands all operate at a `U2FHidFrame` layer, so this also adds a bunch of plumbing to make that all work.
I've tested these with SoloKeys Solo 2 and NitroKey 3A over USB HID. I've tried a few other keys, and they appear to ignore these commands without any issues, but due to the nature of vendor commands this is all very difficult to manage.
I haven't implemented NFC support as that's been very unreliable.
=> Implement some SoloKeys2/Trussed vendor commands

compat_tester/webauthn-rs-demo/src/actors.rs, fido-key-manager/src/main.rs, webauthn-authenticator-rs/examples/authenticate.rs, webauthn-authenticator-rs/src/softpasskey.rs, webauthn-authenticator-rs/src/softtoken.rs, webauthn-authenticator-rs/src/stubs.rs, webauthn-rs-core/src/constants.rs, webauthn-rs-core/src/core.rs, webauthn-rs/src/lib.rs
* Move `DEFAULT_AUTHENTICATOR_TIMEOUT` into `webauthn-rs`, and make `authenticator_timeout` a required parameter for `webauthn_rs_core::Webauthn::unsafe_experts_only`.
* Moves default timeouts into our recommended interface, so that the value of that default isn't hidden behind internal interfaces.
* Fixes a documentation build breakage caused by #385.
* Changes the default timeout from 1 minute to **5 minutes**, per Webauthn-3 recommendations.
* Adds accessibility and UX concerns to the `timeout` documentation.
* Add `PhantomData` to `webauthn_authenticator_rs::stubs`.
Sometime in the last few months, has been a change in Rust Nightly which makes unused type parameters a hard error when documenting; and we rely on Nightly for [`doc_cfg`][0] and [`doc_auto_cfg`][1] on docs.rs.
[0]: …
=> WIP: fixing documentation in CI

cable-tunnel-server/frontend/src/main.rs, fido-hid-rs/src/descriptors.rs, fido-hid-rs/src/linux/mod.rs, fido-key-manager/src/main.rs, webauthn-authenticator-rs/examples/cable_domain.rs, webauthn-authenticator-rs/src/bluetooth/framing.rs, webauthn-authenticator-rs/src/cable/base10.rs, webauthn-authenticator-rs/src/ctap2/ctap21.rs, webauthn-authenticator-rs/src/nfc/atr.rs, webauthn-authenticator-rs/src/transport/any.rs
=> Fix some clippy warnings

attestation-ca/src/lib.rs, webauthn-authenticator-rs/src/softtoken.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/internals.rs, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
This finalises what is required for Kanidm for Webauthn attestation. Being used in "anger" showed a number of smaller issues around the attestation paths and code base. 
=> 20231129 attestation finalisation

webauthn-rs/src/interface.rs
=> One line fix - missing cfg

attestation-ca/src/lib.rs, compat_tester/webauthn-rs-demo/src/actors.rs, fido-key-manager/src/main.rs, sshkey-attest/src/lib.rs, webauthn-authenticator-rs/examples/authenticate.rs, webauthn-authenticator-rs/src/softpasskey.rs, webauthn-authenticator-rs/src/softtoken.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-core/src/lib.rs, webauthn-rs-proto/src/options.rs, webauthn-rs/Cargo.toml, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
Fixes #264 - this cleans up some of the older "safe" interfaces in core since they now all belong in webauthn-rs. This removes some old comments and also hides some modules. Finally some other functions are moved to more contextually relevant places. 
=> 20231215 264 cleanup

fido-key-manager/src/main.rs, webauthn-authenticator-rs/examples/authenticate.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-proto/src/attest.rs, webauthn-rs-proto/src/cose.rs
Fixes #399 - Adds eddsa support
=> Add EDDSA support

Cargo.toml, webauthn-rs-core/Cargo.toml, webauthn-rs-core/src/fake.rs, webauthn-rs-core/src/lib.rs, webauthn-rs/src/lib.rs
Fixes #362 - adds a fake credential ID generator so that RP's may choose to implement account enumeration defences.
=> Add fake credential generator interfaces

Cargo.toml
`clap` 4.5.0 wants rustc 1.74, but our MSRV is still 1.70:
```
error: package `clap_derive v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap_derive@4.5.0 --precise ver
where `ver` is the latest version of `clap_derive` supporting rustc 1.70.0
Error: Process completed with exit code 101.
```
=> Pin clap to 4.4.18 (last version supporting rustc 1.70.0)

attestation-ca/Cargo.toml, attestation-ca/build.rs, webauthn-rs-core/Cargo.toml, webauthn-rs-core/build.rs
[The `webauthn-rs` OpenSSL policy](https://github.com/kanidm/webauthn-rs/blob/master/OpenSSL.md) is currently only "enforced" for `webauthn-authenticator-rs`.
This PR adds OpenSSL version number checks to `attestation-ca` and `webauthn-rs-core` using `OPENSSL_VERSION_NUMBER`. Every other package in this repo with an OpenSSL dependency depends on one of these two packages, so can be handled transitively.
This will make builds fail with OpenSSL v1.x, in line with [our OpenSSL policy](https://github.com/kanidm/webauthn-rs/blob/master/OpenSSL.md).
We don't currently support OpenSSL alternatives, but I've attempted to avoid breaking them with this PR:
- [BoringSSL sets `OPENSSL_VERSION_NUMBER` to whichever it's targetting](https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md), so …
=> Add build-time OpenSSL version checks

OpenSSL.md
The upstream `openssl-src` crate now supports v3, so this works correctly.
Fixes #
=> Update outdated OpenSSL vendoring doc

base64urlsafedata/src/lib.rs, base64urlsafedata/src/tests.rs, tutorial/server/actix_web/Cargo.toml, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/crypto.rs, webauthn-rs-core/src/internals.rs, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
* Updates `actix_web` and `once_cell` to pick up `ahash>=0.8.7` (https://github.com/tkaitchuck/aHash/issues/188), as older versions are broken on nightly.
* Removes redundant imports, which are now an error on nightly.
* Expose optional features / types with `any(all(doc, not(doctest)), feature(...))` so that documentation links always work.
=> Fix building on nightly, broken doc links

.github/workflows/ci.yml
Fixes #427; works around https://github.com/rustwasm/wasm-bindgen/issues/3918 while keeping MSRV as-is.
=> Use bumpalo 3.14.0 in CI (#427)

tutorial/server/tide/src/main.rs, webauthn-rs-core/src/interface.rs, webauthn-rs-proto/src/attest.rs, webauthn-rs/src/interface.rs, webauthn-rs/src/lib.rs
These are various spelling fixes, etc. I made while reading comments as I wrote `webauthn-rp-proxy`.  (I used to be a copy editor, and can't help myself.)  I figured I'd pass them along in case they were helpful.
Fixes #
- [x ] cargo test has been run and passes
- [ N/A] documentation has been updated with relevant examples (if relevant)
=> Fix spelling, etc.

webauthn-authenticator-rs/src/mozilla.rs
Developers building on this crate do not necessarily need logging to occur over `println!` when authenticating 2FA, so this commit replaces the print macros with logging macros
Fixes #
=> Replace `println!` from library functions with configurable logging

.github/workflows/ci.yml, fido-key-manager/Cargo.toml, fido-key-manager/README.md, fido-key-manager/src/main.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/ctap2/ctap20.rs, webauthn-authenticator-rs/src/ctap2/mod.rs, webauthn-authenticator-rs/src/ctap2/yubikey.rs, webauthn-authenticator-rs/src/lib.rs, webauthn-authenticator-rs/src/tlv/ber.rs, webauthn-authenticator-rs/src/tlv/mod.rs, webauthn-authenticator-rs/src/transport/mod.rs, webauthn-authenticator-rs/src/transport/yubikey.rs, webauthn-authenticator-rs/src/usb/mod.rs, webauthn-authenticator-rs/src/usb/yubikey.rs
This adds support for reading the configuration of a YubiKey 5 series over USB with the FIDO2 interface, and a custom BER-TLV parser for YubiKey's not-quite-BER-TLV configuration format.
This is similar to #377.
=> YubiKey 5 vendor commands

webauthn-rs-proto/src/extensions.rs
Fixes #421 - make the credProps flag public. 
=> Make rk flag public

Cargo.toml, attestation-ca/Cargo.toml, sshkey-attest/Cargo.toml, sshkey-attest/src/proto.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-rp-proxy/Cargo.toml, webauthn-rp-proxy/README.md
As is tradition, during a release you find everything that doesn't work like git dependencies, missing versions in the workspace, missing items in Cargo.toml etc. This is a smattering of smaller tidy ups to fix these during the cargo publish process. 
=> Things that you only find during a release

compat_tester/webauthn-rs-demo/src/actors.rs, fido-key-manager/Cargo.toml, fido-key-manager/build.rs, fido-mds/src/mds.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/nfc/mod.rs, webauthn-rs-proto/src/wasm.rs
A number of warnings were emitted by newer versions of rust that were preventing successful build of a number of tools. This PR resolves those warnings.
=> Resolve compilation warnings in fido-mds-tools

fido-mds/src/lib.rs, fido-mds/src/mds.rs, fido-mds/src/patch.rs
This updates the MDS to support undocumented FIDO elements that were added without documentation in the relevant specifications.
This also updates the mds tool to support filtering of compromised devices that FIDO haven't acted on.
Fixes #451 Fixes #450 Fixes #449
=> Update MDS to support undocumented FIDO additions

.github/workflows/ci.yml, Cargo.toml, compat_tester/webauthn-rs-demo-shared/Cargo.toml, compat_tester/webauthn-rs-demo-wasm/Cargo.toml, compat_tester/webauthn-rs-demo/Cargo.toml, tutorial/wasm/Cargo.toml
=> Update MSRV to 1.79

.github/workflows/ci.yml, Cargo.toml
`fido-hid-rs` has a transitive build dependency on `home`:
```
% cargo tree -i home
home v0.5.9
└── which v4.4.2
└── bindgen v0.65.1
[build-dependencies]
└── fido-hid-rs v0.5.0
```
This now [fails in CI on `rustc` 1.79](https://github.com/kanidm/webauthn-rs/actions/runs/12387201838/job/34576258939#step:8:407), which pulls in `home@0.5.11`:
```
error: rustc 1.79.0 is not supported by the following package:
home@0.5.11 requires rustc 1.81
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.79.0
```
MSRV has been bumped by point releases in https://github.com/rust-lang/cargo/pull/14867 and https://github.com/rust-lang/cargo/pull/14871
`home@0.5.9` is …
=> Bump MSRV to 1.81 to match home@0.5.11

Cargo.toml, cable-tunnel-server/backend/Cargo.toml, cable-tunnel-server/backend/src/main.rs, cable-tunnel-server/common/Cargo.toml, cable-tunnel-server/common/src/lib.rs, cable-tunnel-server/frontend/Cargo.toml, cable-tunnel-server/frontend/src/main.rs
**Note:** it compiles, but I need to test with physical hardware.
Upgrades `http`, `http-body-util` and `hyper` to current versions.
`hyper` switched from using Tokio traits to their own custom traits [a while ago](https://github.com/hyperium/hyper/issues/3110), but have an adapter to Tokio traits (`hyper-util`). So this switches everything to use the adapter.
Related to #444
=> Upgrade hyper/http, use new APIs

fido-mds-tool/src/main.rs, fido-mds/src/mds.rs
It would be lovely if FIDO stopped changing their MDS formaT on days ending in 'y'.
=> 20241218 more mds clownshoes

tutorial/Makefile
Fixes #469
Remove the wasm build from the axum tutorial, as it defaults to the js display anyway.
=> fix axum tutorial in makefile

Cargo.toml, tutorial/Makefile, tutorial/server/axum/Cargo.toml, tutorial/server/axum/README.md, tutorial/server/axum/assets/js/index.html, tutorial/server/axum/assets/wasm/index.html, tutorial/server/axum/src/main.rs
=> 469 part deux

webauthn-authenticator-rs/src/usb/mod.rs, webauthn-authenticator-rs/src/usb/responses.rs
This adds USB-HID logic for detecting `CTAPHID_WINK` support.
Ref: https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#usb-hid-init
---
=> authenticator/usb: detect wink capability

webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/error.rs
This allows easier error-handling for consumers, via stdlib `Error` trait.
=> authenticator: use thiserror for `WebauthnCError`

.github/workflows/ci.yml, webauthn-rs-proto/src/options.rs
Fixes #
Hi team, thanks for providing this very helpful crate! I've submitted this PR to address a bug I encountered. I'm hoping this proposed fix can be reviewed and merged soon.
What fixed: `PublicKeyCredentialHint` must be in kebab-case format according to [documentation](https://www.w3.org/TR/webauthn-3/#enum-hints)
=> Fix PublicKeyCredentialHints serde

cable-tunnel-server/backend/src/main.rs, sshkey-attest/src/lib.rs, webauthn-authenticator-rs/src/nfc/tlv.rs, webauthn-authenticator-rs/src/win10/cose.rs, webauthn-rs-core/src/attestation.rs, webauthn-rs-core/src/core.rs, webauthn-rs-core/src/error.rs, webauthn-rs/src/interface.rs
The word `elligibility` is actually spelled with one `l`: `eligibility`
I came across this by reading an error message in another project and found out that it actually came from this code.
This PR fixes the spelling. The only thing I was not quite sure about was changing the error constant, but this crate is still 0.y.z, thus breaking changes are allowed according to semver.
=> fix: elligibility -> eligibility

fido-mds/src/lib.rs, fido-mds/src/mds.rs, webauthn-authenticator-rs/Cargo.toml, webauthn-authenticator-rs/src/softtoken.rs
If we use two softtokens in a single test, openssl can't handle this as it id's CA's by subject DN, and our previous DN's were always the same between two softtokens.
This adds a UUID to the softtoken CA DN so that openssl can resolve this properly in tests.
=> Uniquely ID softtokens
