kanidm/webauthn-rs

- Cargo.toml
- README.md
- examples/actix/actors.rs
- examples/actix/crypto.rs
- examples/actix/main.rs
- src/attestation.rs
- src/constants.rs
- src/crypto.rs
- src/ephemeral.rs
- src/error.rs
- src/lib.rs
- src/proto.rs
Implements #19 improve api ergonomics .
> 20200207 update webauthn api

- Cargo.toml
- examples/actix/actors.rs
- examples/actix/main.rs
- src/attestation.rs
- src/crypto.rs
- src/lib.rs
> actix update

- examples/actix/actors.rs
- src/attestation.rs
- src/lib.rs
- src/proto.rs
> use struct init shorthand in lib.rs

- examples/tide/main.rs
- src/error.rs
- src/lib.rs
> reject empty userids in registration

- src/attestation.rs
- src/crypto.rs
- src/error.rs
> Apple Anonymous Attestation Step 5

- designs/authentication-use-cases.md
> Add doc re auth use cases

- src/core.rs
Relates #73 - this is a review of our registration and authentication code to ensure that we have followed the steps as laid out in level 2 of the webauthn specification.
> Verify we have implemented Level 2 of RP

- examples/tide/README.md
- src/core.rs
- src/ephemeral.rs
- src/proto.rs
Some documentation findings from doing the requested webauthn-rs review (bsc#1187632)
> documentation: fix some typos and inconsistencies

- webauthn-rs-core/src/attestation.rs
- webauthn-rs-core/src/core.rs
I have extracted the Credential::new calls from the attestation verification functions because they code is largely duplicated and parameters are passed to it that are otherwise unused by the verification procedures. Also it follows the output from the specs more closely:
> Verification procedure: The procedure for verifying an [attestation statement](https://www.w3.org/TR/webauthn-2/#attestation-statement), which takes the following verification procedure inputs:
> - attStmt: The [attestation statement](https://www.w3.org/TR/webauthn-2/#attestation-statement) structure
> - authenticatorData: The [authenticator data](https://www.w3.org/TR/webauthn-2/#authenticator-data) claimed to have been used for the attestation
> - clientDataHash: The [hash of the serialized client …
> Extract credential creation from attestation verification functions (2)

- README.md
- webauthn-rs-core/src/core.rs
- webauthn-rs/src/lib.rs
Fixes #82 - A review of our implementation was carried out to ensure the core was compliant to level 3.
> Update to check we are level3 compliant

- webauthn-rs-core/src/internals.rs
As discussed in #105, let's stop checking if the first byte of the aaguid is zero as this yields a lot of false positives. Instead, let's check if the `cred_id_len` is longer than it should be.
> Change aaguid first zero byte warning

- webauthn-rs-core/Cargo.toml
- webauthn-rs-core/src/crypto.rs
- webauthn-rs-core/src/internals.rs
> Verify tpm certificate requirements

- webauthn-rs-core/src/crypto.rs
- webauthn-rs-core/src/internals.rs
We were trying to parse 4 bytes out of the subject alternative name
manufactuerer field for the manufacturer, but the data is an 8-byte string
consisting of 8 hex-digits constituting the 4-byte code.
Additionally, it turns out we were making our `cred_id_len <= remaining_bytes`
check too late---by the time we made the check we had already consumed more
bytes out of the input.
Implements # .
> Fix a problem with the tpm attest certification validation

- webauthn-rs-core/src/interface.rs
- webauthn-rs-core/src/internals.rs
I didn't actually apply the review comments because I'm silly ^^
> 106 client extension handling

- webauthn-authenticator-rs/src/lib.rs
- webauthn-rs-core/src/interface.rs
- webauthn-rs-proto/src/extensions.rs
- webauthn-rs/src/interface.rs
- webauthn-rs/src/lib.rs
Relates #127 improve some aspects of the docs. I still need to write a "tutorial" on usage. 
> Improve docs

- webauthn-rs-core/src/crypto.rs
> Certificate Validation for Packed

- .gitignore
- CONTRIBUTORS.md
- Cargo.toml
- tutorial/server/axum/Cargo.toml
- tutorial/server/axum/src/auth.rs
- tutorial/server/axum/src/error.rs
- tutorial/server/axum/src/file.rs
- tutorial/server/axum/src/main.rs
- tutorial/server/axum/src/startup.rs
- tutorial/server/tide/Cargo.toml
- tutorial/server/tide/src/main.rs
Hiya!
I made a version of the tutorial that uses Axum instead of tide! I also reorganized the tutorial folder to allow different server implementations.
I'd recommend adding a section about the tutorial to the README, but I didn't do that here.
Fixes #
- Added axum version of tutorial site
- Structured tutorial folder a bit
> Commited an axum version of the tutorial!

- compat_tester/webauthn-rs-demo-shared/src/lib.rs
- compat_tester/webauthn-rs-demo-wasm/src/demo.rs
- compat_tester/webauthn-rs-demo/src/actors.rs
- tutorial/server/axum/Cargo.toml
- tutorial/server/axum/src/auth.rs
- tutorial/server/axum/src/startup.rs
- tutorial/server/tide/src/main.rs
- webauthn-rs/src/interface.rs
- webauthn-rs/src/lib.rs
More cleanups, rename Passkey to match the correct casing, add some small traits found through "using in anger".
> 20220712 kanidm integration feedback

- webauthn-rs/src/lib.rs
from discussion on matrix. not sure if this wording is good but hopefully useful.
> fix docs about what you need to do with securitykey authentication

- compat_tester/webauthn-rs-demo/Cargo.toml
- compat_tester/webauthn-rs-demo/src/actors.rs
- webauthn-authenticator-rs/src/softpasskey.rs
- webauthn-authenticator-rs/src/softtoken.rs
- webauthn-rs-core/Cargo.toml
- webauthn-rs-core/src/core.rs
- webauthn-rs-core/src/crypto.rs
- webauthn-rs/Cargo.toml
- webauthn-rs/src/interface.rs
- webauthn-rs/src/lib.rs
> Update docs, apply feedback

- webauthn-authenticator-rs/src/lib.rs
- webauthn-authenticator-rs/src/nfc/mod.rs
Update some nfc code to get this working again.
> Fixes for nfc

- .github/workflows/ci.yml
- Cargo.toml
- authenticator-cli/Cargo.toml
- authenticator-cli/src/main.rs
- fido-mds-tool/Cargo.toml
- fido-mds-tool/src/main.rs
- fido-mds/Cargo.toml
- fido-mds/src/lib.rs
- fido-mds/src/mds.rs
Add support to parse the fido metadata service "blob". There are a number of issues with the data in the MDS, and these have been reported. 
> 20220805 fido mds

- webauthn-authenticator-rs/src/softtoken.rs
> Remove some traces that break on old ubuntu

- webauthn-rs/src/lib.rs
> Fix small typo in docs

- authenticator-cli/Cargo.toml
- fido-mds-tool/Cargo.toml
- fido-mds/Cargo.toml
- webauthn-authenticator-rs/Cargo.toml
- webauthn-authenticator-rs/src/u2fhid.rs
- webauthn-rs-core/Cargo.toml
- webauthn-rs-proto/Cargo.toml
- webauthn-rs/Cargo.toml
- webauthn-rs/src/interface.rs
Fixes a minor issue with warning during publishing, and stops relying on git deps for authenticator-rs
> Release 0.4.5

- authenticator-cli/src/main.rs
- webauthn-rs/src/lib.rs
> some example docs updates

- fido-mds/src/mds.rs
- webauthn-rs/src/interface.rs
- webauthn-rs/src/lib.rs
Fixes #187 significantly improves the docs related to seralisation. 
> Improve remaining docs

- webauthn-rs-core/src/core.rs
- webauthn-rs/src/lib.rs
Fixes https://github.com/kanidm/webauthn-rs/issues/193
> add facet origins

- .github/workflows/ci.yml
- base64urlsafedata/src/lib.rs
- clippy.toml
- compat_tester/webauthn-rs-demo/src/actors.rs
- fido-mds/src/lib.rs
- fido-mds/src/mds.rs
- tutorial/wasm/Cargo.toml
- tutorial/wasm/src/lib.rs
- webauthn-authenticator-rs/src/cbor/get_info.rs
- webauthn-authenticator-rs/src/cbor/make_credential.rs
- webauthn-authenticator-rs/src/cbor/mod.rs
- webauthn-authenticator-rs/src/softpasskey.rs
- webauthn-authenticator-rs/src/softtoken.rs
- webauthn-rs-core/src/core.rs
- webauthn-rs-core/src/crypto.rs
- webauthn-rs-core/src/internals.rs
- webauthn-rs-proto/Cargo.toml
- webauthn-rs-proto/src/attest.rs
- webauthn-rs-proto/src/auth.rs
- webauthn-rs-proto/src/options.rs
got `clippy --all-targets` to pass :sweat:
> fix jsvalue serde issue & clippy lints, run ci on prs

- webauthn-rs-core/src/attestation.rs
Fixes a minor clippy lint that's stopping the CI
> clippy calming

- .github/ISSUE_TEMPLATE/an_idea_or_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/security_report.md
- SECURITY.md
Adding templates and a security policy
> such template like wow

- webauthn-rs/src/lib.rs
> Fix up feature flag

- fido-mds-tool/src/main.rs
- fido-mds/src/lib.rs
- fido-mds/src/mds.rs
Improves the extended output of the fido metadata tool.
> Improve some details of the listing tool

- .github/workflows/ci.yml
- fido-mds-tool/src/main.rs
- webauthn-authenticator-rs/src/ctap2/ctap20.rs
y'all might wanna look into setting that github token though
> don't cancel all ci runs when one fails, and fix lints

- README.md
> Docs - fixes link to core crate in README

- webauthn-rs-core/Cargo.toml
- webauthn-rs-core/src/core.rs
- webauthn-rs-core/src/crypto.rs
- webauthn-rs/Cargo.toml
- webauthn-rs/src/lib.rs
Fixes #245 - remove insecure rsa-sha1 
> 245 disable rs1

- webauthn-authenticator-rs/src/ctap2/commands/get_info.rs
- webauthn-authenticator-rs/src/softtoken.rs
- webauthn-authenticator-rs/src/usb/responses.rs
> Make aaguid a Uuid

- CODEOWNERS
> Add Micolous to codeowners

- webauthn-authenticator-rs/examples/key_manager/main.rs
Use display rather that debug for this output
> display rather than debug

- tutorial/server/tide/src/main.rs
> Improve tide server debug output for testing

- webauthn-rs-core/src/core.rs
- webauthn-rs/src/lib.rs
> making a basic test for a webauthn object from a chrome extension

- webauthn-rs/src/interface.rs
- webauthn-rs/src/lib.rs
> Add getter to read public key from passkey credential

- .github/workflows/ci.yml
- Cargo.toml
- fido-key-manager/Cargo.toml
- fido-key-manager/README.md
- fido-key-manager/build.rs
- fido-key-manager/manifest.xml
- fido-key-manager/src/main.rs
> make key_manager standalone

- webauthn-authenticator-rs/src/nfc/mod.rs
- webauthn-authenticator-rs/src/transport/any.rs
By default, Windows runs the [Smart Card service][3] (`SCardSvr`) in "Manual (Triggered)" start-up mode. Rather than starting the service on boot, Windows will wait for an application to use the PC/SC API.
However, Windows *does not* automatically start `SCardSvr` if:
* there has *never* been a smart card reader (or other CCID interface, such as a Yubikey) connected to the PC
* the user has explicitly disabled the service (in `services.msc`)
Instead, Windows returns an error (`NoService`) when establishing a context (in `NFCReader::new()`):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PcscError(NoService)', fido-key-manager\src\main.rs:222:51
stack backtrace:
0: std::panicking::begin_panic_handler
at …
```
> Handle unavailability of SCardSvr gracefully (on Windows)

- OpenSSL.md
- webauthn-authenticator-rs/build.rs
> add OpenSSL notes and tidy build file

- designs/philosophy.md
This has come up a few times; #277 is just the most recent time :)
Fixes #
> Add design philosophy doc

- webauthn-rs-core/src/core.rs
- webauthn-rs/src/lib.rs
> Add Clone derivation to Webauthn struct

- webauthn-authenticator-rs/examples/authenticate.rs
- webauthn-authenticator-rs/examples/softtoken.rs
- webauthn-authenticator-rs/src/softpasskey.rs
- webauthn-authenticator-rs/src/softtoken.rs
- webauthn-rs/src/interface.rs
> Update soft tokens to allow uv in tests

- webauthn-authenticator-rs/src/win10/credential.rs
- webauthn-rs-proto/src/options.rs
> Accept unknown transports in deserialisation

- webauthn-authenticator-rs/src/cable/tunnel.rs
- webauthn-authenticator-rs/src/ctap2/commands/get_info.rs
> test android and ios CablePostHandshake/GetInfoResponse

- webauthn-authenticator-rs/src/nfc/atr.rs
Fixes an issue where the ATR parser incorrectly treated Y<sub>n</sub> as an absolute value, rather than a bitmask.
This came up parsing [the YubiKey 5C's USB CCID ATR][0], where Y<sub>1</sub> = `0b1111`, which was incorrectly interpreted as containing 7 bytes, when there are actually only 3 bytes (for TA<sub>1</sub>, TB<sub>1</sub> and TC<sub>1</sub>).
This also makes the `Atr::protocols` a `HashSet`, to deal with ATRs that repeat the same protocol multiple times.
[0]: https://smartcard-atr.apdu.fr/parse?ATR=3bfd1300008131fe158073c021c057597562694b657940
> Fix incorrect ATR Y(n) byte parsing

- webauthn-authenticator-rs/src/nfc/mod.rs
* add SoloKey to ignored devices list
* [document Trussed situation][0]
* document `ignored_reader()` better
* add more tests
[0]: https://github.com/trussed-dev/fido-authenticator/issues/38
> Ignore SoloKey CCID devices

- CONTRIBUTORS.md
> Add myself per Firstyear.

- fido-mds/src/mds.rs
Shout outs to whomever added a credential that uses RsassaPkcsv15Sha1Raw in 2024.
> Add RsassaPkcsv15Sha1Raw

- attestation-ca/Cargo.toml
- authenticator-cli/Cargo.toml
- base64urlsafedata/Cargo.toml
- fido-hid-rs/Cargo.toml
- fido-key-manager/Cargo.toml
- fido-mds-tool/Cargo.toml
- fido-mds/Cargo.toml
- sshkey-attest/Cargo.toml
- webauthn-rp-proxy/Cargo.toml
- webauthn-rs-core/Cargo.toml
- webauthn-rs-proto/Cargo.toml
- webauthn-rs/Cargo.toml
> Release 0.5.0

- .github/workflows/ci.yml
- Cargo.toml
- tutorial/server/actix_web/Cargo.toml
- tutorial/server/actix_web/src/handler/mod.rs
- tutorial/server/actix_web/src/handler/serve_wasm.rs
- tutorial/server/actix_web/src/main.rs
- tutorial/server/actix_web/src/session.rs
- tutorial/server/axum/Cargo.toml
- tutorial/server/tide/Cargo.toml
Upgraded actix-web tutorial to compile again.
I've also cleaned up some old code and made it compatible with `actix-sessions` v0.9.
> Fixed actix tutorial

- sshkey-attest/Cargo.toml
- sshkey-attest/README.md
- sshkey-attest/src/proto.rs
> Update ssh keys to latest version

- attestation-ca/build.rs
- base64urlsafedata/src/common.rs
- tutorial/wasm/src/lib.rs
- webauthn-authenticator-rs/src/ctap2/ctap21_cred.rs
- webauthn-rs-core/build.rs
- webauthn-rs-proto/src/options.rs
- webauthn-rs-proto/src/wasm.rs
> Clippy fixes

- Cargo.toml
- attestation-ca/Cargo.toml
- authenticator-cli/Cargo.toml
- base64urlsafedata/Cargo.toml
- fido-hid-rs/Cargo.toml
- fido-key-manager/Cargo.toml
- fido-mds-tool/Cargo.toml
- fido-mds/Cargo.toml
- sshkey-attest/Cargo.toml
- webauthn-authenticator-rs/Cargo.toml
- webauthn-rp-proxy/Cargo.toml
- webauthn-rs-core/Cargo.toml
- webauthn-rs-proto/Cargo.toml
- webauthn-rs/Cargo.toml
Use package version from workspace to make releases easier to create.
> Use workspace for package versions

- Cargo.toml
- compat_tester/webauthn-rs-demo/Cargo.toml
- fido-mds/src/mds.rs
- tutorial/server/tide/Cargo.toml
- webauthn-rs-core/src/attestation.rs
Fixes #443 - Update compact-jwt to latest version.
We still can't release though - @micolous there are a bunch of things that need upgrade around cable here which I don't really want to touch since I don't understand it. Currently, it's actually breaking the ability to run cargo outdated so I can't check if we are missing anything else. 
> 20240717 update deps

- .github/workflows/ci.yml
Fixes a coming deprecation of the Github action
> updating upload-artifact to v4

- fido-mds/src/mds.rs
> 🤡 I love FIDO

- webauthn-authenticator-rs/src/ctap2/ctap20.rs
Works around firmware bugs in Google Titan Key v2 and Token2 T2F2-NFC-Dual where they don't follow the spec properly, by doing the same as what Safari 18.4 and Windows 10 do:
* Always send `pin_uv_auth_param = 1` with FIDO 2.0 selection.
* Don't treat `MissingParameter` as a valid FIDO 2.0 selection response.
Fixes #485
> FIDO 2.0 selection: always send `pin_uv_auth_param = 1`, don't treat `MissingParameter` as a valid response

- Cargo.toml
> Release 5.2

- Cargo.toml
- sshkey-attest/src/lib.rs
- tutorial/server/actix_web/Cargo.toml
- tutorial/server/actix_web/src/handler/index.rs
- tutorial/server/actix_web/src/main.rs
- tutorial/server/actix_web/src/session.rs
- tutorial/server/tide/Cargo.toml
- tutorial/wasm/src/lib.rs
- webauthn-authenticator-rs/src/lib.rs
- webauthn-rp-proxy/Cargo.toml
- webauthn-rs-core/src/lib.rs
- webauthn-rs-proto/src/lib.rs
- webauthn-rs/src/lib.rs
> Cleaning up Actix example startup a little
